version: '3.8'

services:
  betting-system:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FOOTBALL_API_KEY=${FOOTBALL_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - LOG_LEVEL=INFO
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped